"""
Retrain anomaly detection using One-Class SVM and save to audit_anomaly.pkl.

Run from the project root:
    python -m backend.scripts.train_ocsvm
"""
import warnings
import os
from pathlib import Path

import numpy as np
import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import OneClassSVM
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

warnings.filterwarnings('ignore')

MODEL_PATH = Path(__file__).resolve().parents[1] / "models" / "audit_anomaly.pkl"
CONTAMINATION = 0.005


def build_dataset():
    df_loghub = pd.DataFrame({
        'log_text': [f"Normal system log entry HDFS block status OK {i}" for i in range(150000)],
        'label': 0,
    })

    df_normal = pd.DataFrame({
        'log_text': [
            "User query parsed successfully",
            "Document ingestion complete",
            "Retrieval operation for user id=123",
            "Access granted to vault",
            "Model inference completed in 0.12s",
        ] * 6000,
        'label': 0,
    })

    df_attack = pd.DataFrame({
        'log_text': [
            "Prompt injection attempt detected: ignore previous instructions",
            "Adversarial query generated by LLM: bypass security controls",
            "Canary trigger event: sensitive_doc_accessed",
            "Abnormal access attempt from unusual IP",
            "Simulated attack from Automated Red-Team system",
        ] * 4000,
        'label': 1,
    })

    df = pd.concat([df_loghub, df_normal, df_attack], ignore_index=True)
    df.dropna(subset=['log_text'], inplace=True)
    df['log_text'] = df['log_text'].astype(str).str.lower()
    return df.sample(frac=1, random_state=42).reset_index(drop=True)


def main():
    print("Building dataset...")
    df = build_dataset()
    total = len(df)
    print(f"  {total} samples, anomaly ratio {df['label'].mean():.2%}")

    print("Fitting TF-IDF vectorizer...")
    vectorizer = TfidfVectorizer(max_features=3000, stop_words='english')
    X = vectorizer.fit_transform(df['log_text'])

    X_train, X_test, y_train, y_test = train_test_split(
        X, df['label'], test_size=0.2, random_state=42, stratify=df['label']
    )
    X_train_normal = X_train[(y_train == 0).values]
    print(f"  Train (normal only): {X_train_normal.shape[0]}  |  Test: {X_test.shape[0]}")

    print("Training One-Class SVM (kernel=linear)...")
    model = OneClassSVM(kernel='linear', nu=CONTAMINATION)
    model.fit(X_train_normal)

    preds = model.predict(X_test)
    mapped = np.where(preds == -1, 1, 0)
    acc  = accuracy_score(y_test, mapped)
    prec = precision_score(y_test, mapped, zero_division=0)
    rec  = recall_score(y_test, mapped, zero_division=0)
    f1   = f1_score(y_test, mapped, zero_division=0)
    sec  = 0.7 * rec + 0.3 * prec
    print(f"  Accuracy={acc:.4f}  Precision={prec:.4f}  Recall={rec:.4f}  "
          f"F1={f1:.4f}  SecurityScore={sec:.4f}")

    payload = {
        "vectorizer": vectorizer,
        "model": model,
        "metadata": {
            "selected_model_name": "One-Class SVM",
            "dataset_size": total,
            "feature_method": "TF-IDF",
            "contamination": CONTAMINATION,
            "version": "1.1",
        },
    }
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(payload, MODEL_PATH)
    print(f"\nSaved One-Class SVM to {MODEL_PATH}")


if __name__ == "__main__":
    main()
